[build]
command="netlify-extension build -a"
publish = ".ntli/site/static"

[functions]
directory = "src/endpoints"

[dev]
command = "netlify-extension dev"

[[plugins]]
package = "@netlify/netlify-plugin-netlify-extension"